#spring.application.name=sanaz-spring
server:
  port: 8080

spring:
  application:
    name: core banking

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/homeservicev2
    username: Maktab
    password: Maktab123
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 300KB
      max-request-size: 300KB
